#############################################################################
# Makefile for building: projet-si
# Generated by qmake (2.01a) (Qt 4.8.1) on: mer. nov. 14 08:54:03 2012
# Project:  projet-si.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile projet-si.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -DEBUG -g -Wall -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iinclude -I/opt/local/include/opencv/ -I/opt/local/include/ -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib /opt/local/lib/libopencv_calib3d.dylib /opt/local/lib/libopencv_contrib.dylib /opt/local/lib/libopencv_core.dylib /opt/local/lib/libopencv_features2d.dylib /opt/local/lib/libopencv_flann.dylib /opt/local/lib/libopencv_gpu.dylib /opt/local/lib/libopencv_highgui.dylib /opt/local/lib/libopencv_imgproc.dylib /opt/local/lib/libopencv_legacy.dylib /opt/local/lib/libopencv_video.dylib -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = binaryconversionpass.cpp \
		blurpass.cpp \
		houghcircledetectionpass.cpp \
		gaussianblurpass.cpp \
		graylevelpass.cpp \
		videoextractor.cpp \
		imageconverter.cpp \
		imageprocessor.cpp \
		ipass.cpp \
		main.cpp \
		mainwindow.cpp \
		passchain.cpp \
		controller.cpp \
		circle.cpp \
		customcircledetectionpass.cpp \
		roipass.cpp \
		parameterdock.cpp \
		imagescaledialog.cpp \
		customgraphicsscene.cpp \
		videoprocessor.cpp \
		cannyfilterpass.cpp \
		customgraphicsview.cpp \
		angledetectionpass.cpp \
		circledetectionpass.cpp \
		aboutdialog.cpp \
		extractsequencedialog.cpp \
		meanshiftfilterpass.cpp \
		dynamicpasschain.cpp \
		sobelfilterpass.cpp \
		savedialog.cpp moc_videoextractor.cpp \
		moc_imageprocessor.cpp \
		moc_mainwindow.cpp \
		moc_controller.cpp \
		moc_parameterdock.cpp \
		moc_imagescaledialog.cpp \
		moc_customgraphicsscene.cpp \
		moc_videoprocessor.cpp \
		moc_cannyfilterpass.cpp \
		moc_customgraphicsview.cpp \
		moc_aboutdialog.cpp \
		moc_extractsequencedialog.cpp \
		moc_meanshiftfilterpass.cpp \
		moc_dynamicpasschain.cpp \
		moc_sobelfilterpass.cpp \
		moc_savedialog.cpp \
		qrc_toolbar.cpp
OBJECTS       = binaryconversionpass.o \
		blurpass.o \
		houghcircledetectionpass.o \
		gaussianblurpass.o \
		graylevelpass.o \
		videoextractor.o \
		imageconverter.o \
		imageprocessor.o \
		ipass.o \
		main.o \
		mainwindow.o \
		passchain.o \
		controller.o \
		circle.o \
		customcircledetectionpass.o \
		roipass.o \
		parameterdock.o \
		imagescaledialog.o \
		customgraphicsscene.o \
		videoprocessor.o \
		cannyfilterpass.o \
		customgraphicsview.o \
		angledetectionpass.o \
		circledetectionpass.o \
		aboutdialog.o \
		extractsequencedialog.o \
		meanshiftfilterpass.o \
		dynamicpasschain.o \
		sobelfilterpass.o \
		savedialog.o \
		moc_videoextractor.o \
		moc_imageprocessor.o \
		moc_mainwindow.o \
		moc_controller.o \
		moc_parameterdock.o \
		moc_imagescaledialog.o \
		moc_customgraphicsscene.o \
		moc_videoprocessor.o \
		moc_cannyfilterpass.o \
		moc_customgraphicsview.o \
		moc_aboutdialog.o \
		moc_extractsequencedialog.o \
		moc_meanshiftfilterpass.o \
		moc_dynamicpasschain.o \
		moc_sobelfilterpass.o \
		moc_savedialog.o \
		qrc_toolbar.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		projet-si.libs.user \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		projet-si.pro
QMAKE_TARGET  = projet-si
DESTDIR       = 
TARGET        = projet-si

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_parameterdock.h ui_imagescaledialog.h ui_aboutdialog.h ui_extractsequencedialog.h ui_dynamicpasschain.h ui_savedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projet-si.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		projet-si.libs.user \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile projet-si.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
projet-si.libs.user:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile projet-si.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/projet-si1.0.0 || $(MKDIR) .tmp/projet-si1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/projet-si1.0.0/ && $(COPY_FILE) --parents binaryconversionpass.h blurpass.h houghcircledetectionpass.h gaussianblurpass.h graylevelpass.h videoextractor.h imageconverter.h imageprocessor.h ipass.h mainwindow.h passchain.h controller.h circle.h customcircledetectionpass.h roipass.h parameterdock.h imagescaledialog.h customgraphicsscene.h videoprocessor.h cannyfilterpass.h customgraphicsview.h angledetectionpass.h circledetectionpass.h aboutdialog.h extractsequencedialog.h meanshiftfilterpass.h dynamicpasschain.h sobelfilterpass.h savedialog.h .tmp/projet-si1.0.0/ && $(COPY_FILE) --parents toolbar.qrc .tmp/projet-si1.0.0/ && $(COPY_FILE) --parents binaryconversionpass.cpp blurpass.cpp houghcircledetectionpass.cpp gaussianblurpass.cpp graylevelpass.cpp videoextractor.cpp imageconverter.cpp imageprocessor.cpp ipass.cpp main.cpp mainwindow.cpp passchain.cpp controller.cpp circle.cpp customcircledetectionpass.cpp roipass.cpp parameterdock.cpp imagescaledialog.cpp customgraphicsscene.cpp videoprocessor.cpp cannyfilterpass.cpp customgraphicsview.cpp angledetectionpass.cpp circledetectionpass.cpp aboutdialog.cpp extractsequencedialog.cpp meanshiftfilterpass.cpp dynamicpasschain.cpp sobelfilterpass.cpp savedialog.cpp .tmp/projet-si1.0.0/ && $(COPY_FILE) --parents mainwindow.ui parameterdock.ui imagescaledialog.ui aboutdialog.ui extractsequencedialog.ui dynamicpasschain.ui savedialog.ui .tmp/projet-si1.0.0/ && (cd `dirname .tmp/projet-si1.0.0` && $(TAR) projet-si1.0.0.tar projet-si1.0.0 && $(COMPRESS) projet-si1.0.0.tar) && $(MOVE) `dirname .tmp/projet-si1.0.0`/projet-si1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/projet-si1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_videoextractor.cpp moc_imageprocessor.cpp moc_mainwindow.cpp moc_controller.cpp moc_parameterdock.cpp moc_imagescaledialog.cpp moc_customgraphicsscene.cpp moc_videoprocessor.cpp moc_cannyfilterpass.cpp moc_customgraphicsview.cpp moc_aboutdialog.cpp moc_extractsequencedialog.cpp moc_meanshiftfilterpass.cpp moc_dynamicpasschain.cpp moc_sobelfilterpass.cpp moc_savedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_videoextractor.cpp moc_imageprocessor.cpp moc_mainwindow.cpp moc_controller.cpp moc_parameterdock.cpp moc_imagescaledialog.cpp moc_customgraphicsscene.cpp moc_videoprocessor.cpp moc_cannyfilterpass.cpp moc_customgraphicsview.cpp moc_aboutdialog.cpp moc_extractsequencedialog.cpp moc_meanshiftfilterpass.cpp moc_dynamicpasschain.cpp moc_sobelfilterpass.cpp moc_savedialog.cpp
moc_videoextractor.cpp: videoextractor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) videoextractor.h -o moc_videoextractor.cpp

moc_imageprocessor.cpp: passchain.h \
		ipass.h \
		circle.h \
		imageprocessor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imageprocessor.h -o moc_imageprocessor.cpp

moc_mainwindow.cpp: imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_controller.cpp: mainwindow.h \
		imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		parameterdock.h \
		houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h \
		customcircledetectionpass.h \
		angledetectionpass.h \
		cannyfilterpass.h \
		binaryconversionpass.h \
		graylevelpass.h \
		gaussianblurpass.h \
		blurpass.h \
		meanshiftfilterpass.h \
		sobelfilterpass.h \
		imageprocessor.h \
		passchain.h \
		imageconverter.h \
		videoextractor.h \
		videoprocessor.h \
		roipass.h \
		controller.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) controller.h -o moc_controller.cpp

moc_parameterdock.cpp: parameterdock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) parameterdock.h -o moc_parameterdock.cpp

moc_imagescaledialog.cpp: imagescaledialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imagescaledialog.h -o moc_imagescaledialog.cpp

moc_customgraphicsscene.cpp: customgraphicsscene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customgraphicsscene.h -o moc_customgraphicsscene.cpp

moc_videoprocessor.cpp: videoextractor.h \
		videoprocessor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) videoprocessor.h -o moc_videoprocessor.cpp

moc_cannyfilterpass.cpp: ipass.h \
		circle.h \
		cannyfilterpass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cannyfilterpass.h -o moc_cannyfilterpass.cpp

moc_customgraphicsview.cpp: customgraphicsscene.h \
		customgraphicsview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customgraphicsview.h -o moc_customgraphicsview.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_extractsequencedialog.cpp: extractsequencedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) extractsequencedialog.h -o moc_extractsequencedialog.cpp

moc_meanshiftfilterpass.cpp: ipass.h \
		circle.h \
		meanshiftfilterpass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) meanshiftfilterpass.h -o moc_meanshiftfilterpass.cpp

moc_dynamicpasschain.cpp: dynamicpasschain.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dynamicpasschain.h -o moc_dynamicpasschain.cpp

moc_sobelfilterpass.cpp: ipass.h \
		circle.h \
		sobelfilterpass.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sobelfilterpass.h -o moc_sobelfilterpass.cpp

moc_savedialog.cpp: savedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) savedialog.h -o moc_savedialog.cpp

compiler_rcc_make_all: qrc_toolbar.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_toolbar.cpp
qrc_toolbar.cpp: toolbar.qrc \
		images/android.png \
		images/document-import.png \
		images/document-export.png \
		images/cross-circle.png \
		images/network-clouds.png \
		images/document-binary.png \
		images/books-brown.png \
		images/application-terminal.png \
		images/control-double.png \
		images/hand.png \
		images/monitor--pencil.png \
		images/image-saturation-up.png \
		images/image-blur.png \
		images/layer-shape-round.png \
		images/arrow.png \
		images/control.png \
		images/magnifier-zoom-in.png \
		images/cross.png \
		images/arrow-resize-045.png \
		images/selection.png \
		images/ui-list-box.png \
		images/gradient_inverse.png \
		images/folder-open-slide.png \
		images/minus.png \
		images/arrow-180.png \
		images/webcam--arrow.png \
		images/printer-medium.png \
		images/folder-open-film.png \
		images/fire--minus.png \
		images/fire-big.png \
		images/gradient.png \
		images/disk-return-black.png \
		images/application-export.png \
		images/control-pause.png \
		images/image-export.png \
		images/network-ip-local.png \
		images/question.png \
		images/fire--plus.png \
		images/cross-script.png \
		images/plus-button.png \
		images/cursor.png \
		images/magnifier-zoom-fit.png \
		images/control-power.png \
		images/application-list.png \
		images/monitor-window-3d.png \
		images/minus-button.png \
		images/plus.png \
		images/ui-ruler.png \
		images/magnifier-zoom-out.png \
		images/layer-shape-ellipse.png \
		images/films.png \
		images/wrench.png \
		images/layers-alignment-bottom.png \
		images/folder-open-image.png \
		images/image-resize.png \
		images/webcam.png
	/usr/bin/rcc -name toolbar toolbar.qrc -o qrc_toolbar.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_parameterdock.h ui_imagescaledialog.h ui_aboutdialog.h ui_extractsequencedialog.h ui_dynamicpasschain.h ui_savedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_parameterdock.h ui_imagescaledialog.h ui_aboutdialog.h ui_extractsequencedialog.h ui_dynamicpasschain.h ui_savedialog.h
ui_mainwindow.h: mainwindow.ui \
		customgraphicsview.h \
		customgraphicsscene.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_parameterdock.h: parameterdock.ui
	/usr/bin/uic-qt4 parameterdock.ui -o ui_parameterdock.h

ui_imagescaledialog.h: imagescaledialog.ui
	/usr/bin/uic-qt4 imagescaledialog.ui -o ui_imagescaledialog.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h

ui_extractsequencedialog.h: extractsequencedialog.ui
	/usr/bin/uic-qt4 extractsequencedialog.ui -o ui_extractsequencedialog.h

ui_dynamicpasschain.h: dynamicpasschain.ui
	/usr/bin/uic-qt4 dynamicpasschain.ui -o ui_dynamicpasschain.h

ui_savedialog.h: savedialog.ui
	/usr/bin/uic-qt4 savedialog.ui -o ui_savedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

binaryconversionpass.o: binaryconversionpass.cpp binaryconversionpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o binaryconversionpass.o binaryconversionpass.cpp

blurpass.o: blurpass.cpp blurpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blurpass.o blurpass.cpp

houghcircledetectionpass.o: houghcircledetectionpass.cpp houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o houghcircledetectionpass.o houghcircledetectionpass.cpp

gaussianblurpass.o: gaussianblurpass.cpp gaussianblurpass.h \
		blurpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gaussianblurpass.o gaussianblurpass.cpp

graylevelpass.o: graylevelpass.cpp graylevelpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graylevelpass.o graylevelpass.cpp

videoextractor.o: videoextractor.cpp videoextractor.h \
		imageconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoextractor.o videoextractor.cpp

imageconverter.o: imageconverter.cpp imageconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageconverter.o imageconverter.cpp

imageprocessor.o: imageprocessor.cpp imageprocessor.h \
		passchain.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageprocessor.o imageprocessor.cpp

ipass.o: ipass.cpp ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipass.o ipass.cpp

main.o: main.cpp controller.h \
		mainwindow.h \
		imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		parameterdock.h \
		houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h \
		customcircledetectionpass.h \
		angledetectionpass.h \
		cannyfilterpass.h \
		binaryconversionpass.h \
		graylevelpass.h \
		gaussianblurpass.h \
		blurpass.h \
		meanshiftfilterpass.h \
		sobelfilterpass.h \
		imageprocessor.h \
		passchain.h \
		imageconverter.h \
		videoextractor.h \
		videoprocessor.h \
		roipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		ui_mainwindow.h \
		customgraphicsview.h \
		controller.h \
		parameterdock.h \
		houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h \
		customcircledetectionpass.h \
		angledetectionpass.h \
		cannyfilterpass.h \
		binaryconversionpass.h \
		graylevelpass.h \
		gaussianblurpass.h \
		blurpass.h \
		meanshiftfilterpass.h \
		sobelfilterpass.h \
		imageprocessor.h \
		passchain.h \
		imageconverter.h \
		videoextractor.h \
		videoprocessor.h \
		roipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

passchain.o: passchain.cpp passchain.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passchain.o passchain.cpp

controller.o: controller.cpp controller.h \
		mainwindow.h \
		imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		parameterdock.h \
		houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h \
		customcircledetectionpass.h \
		angledetectionpass.h \
		cannyfilterpass.h \
		binaryconversionpass.h \
		graylevelpass.h \
		gaussianblurpass.h \
		blurpass.h \
		meanshiftfilterpass.h \
		sobelfilterpass.h \
		imageprocessor.h \
		passchain.h \
		imageconverter.h \
		videoextractor.h \
		videoprocessor.h \
		roipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

circle.o: circle.cpp circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o circle.o circle.cpp

customcircledetectionpass.o: customcircledetectionpass.cpp customcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customcircledetectionpass.o customcircledetectionpass.cpp

roipass.o: roipass.cpp roipass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roipass.o roipass.cpp

parameterdock.o: parameterdock.cpp parameterdock.h \
		ui_parameterdock.h \
		controller.h \
		mainwindow.h \
		imagescaledialog.h \
		aboutdialog.h \
		extractsequencedialog.h \
		customgraphicsscene.h \
		savedialog.h \
		dynamicpasschain.h \
		houghcircledetectionpass.h \
		circledetectionpass.h \
		circle.h \
		ipass.h \
		customcircledetectionpass.h \
		angledetectionpass.h \
		cannyfilterpass.h \
		binaryconversionpass.h \
		graylevelpass.h \
		gaussianblurpass.h \
		blurpass.h \
		meanshiftfilterpass.h \
		sobelfilterpass.h \
		imageprocessor.h \
		passchain.h \
		imageconverter.h \
		videoextractor.h \
		videoprocessor.h \
		roipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterdock.o parameterdock.cpp

imagescaledialog.o: imagescaledialog.cpp imagescaledialog.h \
		ui_imagescaledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagescaledialog.o imagescaledialog.cpp

customgraphicsscene.o: customgraphicsscene.cpp customgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customgraphicsscene.o customgraphicsscene.cpp

videoprocessor.o: videoprocessor.cpp videoprocessor.h \
		videoextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videoprocessor.o videoprocessor.cpp

cannyfilterpass.o: cannyfilterpass.cpp cannyfilterpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cannyfilterpass.o cannyfilterpass.cpp

customgraphicsview.o: customgraphicsview.cpp customgraphicsview.h \
		customgraphicsscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customgraphicsview.o customgraphicsview.cpp

angledetectionpass.o: angledetectionpass.cpp angledetectionpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o angledetectionpass.o angledetectionpass.cpp

circledetectionpass.o: circledetectionpass.cpp circledetectionpass.h \
		circle.h \
		ipass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o circledetectionpass.o circledetectionpass.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

extractsequencedialog.o: extractsequencedialog.cpp extractsequencedialog.h \
		ui_extractsequencedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o extractsequencedialog.o extractsequencedialog.cpp

meanshiftfilterpass.o: meanshiftfilterpass.cpp meanshiftfilterpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meanshiftfilterpass.o meanshiftfilterpass.cpp

dynamicpasschain.o: dynamicpasschain.cpp dynamicpasschain.h \
		ui_dynamicpasschain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dynamicpasschain.o dynamicpasschain.cpp

sobelfilterpass.o: sobelfilterpass.cpp sobelfilterpass.h \
		ipass.h \
		circle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sobelfilterpass.o sobelfilterpass.cpp

savedialog.o: savedialog.cpp savedialog.h \
		ui_savedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savedialog.o savedialog.cpp

moc_videoextractor.o: moc_videoextractor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videoextractor.o moc_videoextractor.cpp

moc_imageprocessor.o: moc_imageprocessor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageprocessor.o moc_imageprocessor.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_parameterdock.o: moc_parameterdock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameterdock.o moc_parameterdock.cpp

moc_imagescaledialog.o: moc_imagescaledialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagescaledialog.o moc_imagescaledialog.cpp

moc_customgraphicsscene.o: moc_customgraphicsscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customgraphicsscene.o moc_customgraphicsscene.cpp

moc_videoprocessor.o: moc_videoprocessor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videoprocessor.o moc_videoprocessor.cpp

moc_cannyfilterpass.o: moc_cannyfilterpass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cannyfilterpass.o moc_cannyfilterpass.cpp

moc_customgraphicsview.o: moc_customgraphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customgraphicsview.o moc_customgraphicsview.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_extractsequencedialog.o: moc_extractsequencedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_extractsequencedialog.o moc_extractsequencedialog.cpp

moc_meanshiftfilterpass.o: moc_meanshiftfilterpass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_meanshiftfilterpass.o moc_meanshiftfilterpass.cpp

moc_dynamicpasschain.o: moc_dynamicpasschain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dynamicpasschain.o moc_dynamicpasschain.cpp

moc_sobelfilterpass.o: moc_sobelfilterpass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sobelfilterpass.o moc_sobelfilterpass.cpp

moc_savedialog.o: moc_savedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savedialog.o moc_savedialog.cpp

qrc_toolbar.o: qrc_toolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_toolbar.o qrc_toolbar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

